const constants = {
  API_CALL_ERROR: "CALL_TO_API_FAILED",
  JWT_ERROR: "JWT_ERROR",
  NO_EVENT_ERROR: "NO_EVENT",
  NO_METADATA_ERROR: "NO_METADATA",
  NO_DATA_ERROR: "NO_DATA",
  GET_PUBLIC_KEY_API_URL: "/ums/v1/security/public-key",
};


const cloudConstants = {
  BIOT_JWT_PERMISSION: process.env.BIOT_JWT_PERMISSION_NOTIFICATION || process.env.BIOT_JWT_PERMISSION_INTERCEPTION,
  BIOT_APP_NAME: process.env.BIOT_APP_NAME,
  BIOT_BASE_URL: process.env.BIOT_BASE_URL,
  BIOT_SERVICE_USER_ID: process.env.BIOT_SERVICE_USER_ID,
  BIOT_SERVICE_USER_SECRET_KEY: process.env.BIOT_SERVICE_USER_SECRET_KEY,
  AWS_EXECUTION_ENV: process.env.AWS_EXECUTION_ENV,
  BIOT_SHOULD_VALIDATE_JWT: !!process.env.BIOT_SHOULD_VALIDATE_JWT
    ? process.env.BIOT_SHOULD_VALIDATE_JWT === "false"
      ? false
      : true
    : true,
  BIOT_SERVICE_ENVIRONMENT: process.env.BIOT_SERVICE_ENVIRONMENT,
};

const localDevConstants = {
  BIOT_JWT_PERMISSION: null,
  BIOT_APP_NAME: "BioT Lambda seed",
  BIOT_BASE_URL: null,
  BIOT_SERVICE_USER_ID: null,
  BIOT_SERVICE_USER_SECRET_KEY: null,
  AWS_EXECUTION_ENV: "DEV",
  BIOT_SHOULD_VALIDATE_JWT: true,
  BIOT_SERVICE_ENVIRONMENT: "int",
};

const environmentConstants = process.env.AWS_EXECUTION_ENV
  ? cloudConstants
  : localDevConstants;

const {
  API_CALL_ERROR,
  JWT_ERROR,
  NO_EVENT_ERROR,
  NO_METADATA_ERROR,
  NO_DATA_ERROR,
  GET_PUBLIC_KEY_API_URL,
} = constants;

const {
  BIOT_JWT_PERMISSION,
  BIOT_APP_NAME,
  BIOT_BASE_URL,
  BIOT_SERVICE_USER_ID,
  BIOT_SERVICE_USER_SECRET_KEY,
  AWS_EXECUTION_ENV,
  BIOT_SHOULD_VALIDATE_JWT,
  BIOT_SERVICE_ENVIRONMENT,
} = environmentConstants;

export {
  BIOT_JWT_PERMISSION,
  BIOT_APP_NAME,
  BIOT_BASE_URL,
  BIOT_SERVICE_USER_ID,
  BIOT_SERVICE_USER_SECRET_KEY,
  API_CALL_ERROR,
  JWT_ERROR,
  NO_EVENT_ERROR,
  NO_METADATA_ERROR,
  NO_DATA_ERROR,
  AWS_EXECUTION_ENV,
  BIOT_SHOULD_VALIDATE_JWT,
  BIOT_SERVICE_ENVIRONMENT,
  GET_PUBLIC_KEY_API_URL,
};
